# Generated by Django 4.2.25 on 2025-10-08 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lugares', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ruta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distancia_km', models.DecimalField(decimal_places=2, max_digits=6)),
                ('tiempo_minutos', models.IntegerField()),
                ('medio_transporte', models.CharField(choices=[('caminando', 'Caminando'), ('auto', 'Auto'), ('bus', 'Bus'), ('taxi', 'Taxi'), ('bicicleta', 'Bicicleta')], max_length=20)),
                ('costo_transporte', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('activo', models.BooleanField(default=True)),
                ('destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rutas_hacia', to='lugares.destino')),
                ('origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rutas_desde', to='lugares.destino')),
            ],
            options={
                'verbose_name': 'Ruta',
                'verbose_name_plural': 'Rutas',
                'unique_together': {('origen', 'destino', 'medio_transporte')},
            },
        ),
    ]
