# Generated by Django 4.2.25 on 2025-10-08 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ItemItinerario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.IntegerField()),
                ('dia', models.IntegerField(help_text='Día del itinerario (1, 2, 3...)')),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('notas', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Item de Itinerario',
                'verbose_name_plural': 'Items de Itinerario',
                'ordering': ['itinerario', 'orden'],
            },
        ),
        migrations.CreateModel(
            name='Itinerario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('costo_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('tiempo_total_minutos', models.IntegerField(default=0)),
                ('distancia_total_km', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('confirmado', 'Confirmado'), ('en_proceso', 'En Proceso'), ('completado', 'Completado'), ('cancelado', 'Cancelado')], default='borrador', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Itinerario',
                'verbose_name_plural': 'Itinerarios',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
