# Generated by Django 4.2.25 on 2025-10-08 12:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('itinerarios', '0001_initial'),
        ('lugares', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='itinerario',
            name='turista',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itinerarios', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='itemitinerario',
            name='destino',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lugares.destino'),
        ),
        migrations.AddField(
            model_name='itemitinerario',
            name='itinerario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='itinerarios.itinerario'),
        ),
        migrations.AlterUniqueTogether(
            name='itemitinerario',
            unique_together={('itinerario', 'orden')},
        ),
    ]
