# Generated by Django 4.2.25 on 2025-10-08 12:19

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('icono', models.CharField(blank=True, help_text='Clase CSS para icono', max_length=50)),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
            },
        ),
        migrations.CreateModel(
            name='Destino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('latitud', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitud', models.DecimalField(decimal_places=6, max_digits=9)),
                ('direccion', models.CharField(blank=True, max_length=255)),
                ('costo_entrada', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('tiempo_visita_estimado', models.IntegerField(help_text='Tiempo estimado en minutos')),
                ('tags_preferencias', models.JSONField(blank=True, default=list, help_text='Tags: playa, museos, gastronomia, etc.')),
                ('calificacion', models.DecimalField(decimal_places=2, default=0.0, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('imagen_principal', models.ImageField(blank=True, null=True, upload_to='destinos/')),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='destinos', to='lugares.categoria')),
            ],
            options={
                'verbose_name': 'Destino',
                'verbose_name_plural': 'Destinos',
                'ordering': ['-calificacion', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='ImagenDestino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='destinos/galeria/')),
                ('descripcion', models.CharField(blank=True, max_length=255)),
                ('orden', models.IntegerField(default=0)),
                ('destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='lugares.destino')),
            ],
            options={
                'verbose_name': 'Imagen de Destino',
                'verbose_name_plural': 'Imágenes de Destinos',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('visita_guiada', 'Visita Guiada'), ('degustacion', 'Degustación'), ('deporte', 'Deporte/Aventura'), ('cultural', 'Cultural'), ('entretenimiento', 'Entretenimiento')], max_length=50)),
                ('descripcion', models.TextField()),
                ('costo', models.DecimalField(decimal_places=2, max_digits=8)),
                ('duracion_minutos', models.IntegerField()),
                ('disponible', models.BooleanField(default=True)),
                ('destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividades', to='lugares.destino')),
            ],
            options={
                'verbose_name': 'Actividad',
                'verbose_name_plural': 'Actividades',
            },
        ),
    ]
