# Generated by Django 4.2.25 on 2025-10-24 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lugares', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destino',
            name='imagen_principal',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='imagendestino',
            name='imagen',
            field=models.URLField(max_length=500),
        ),
    ]
