# Generated by Django 4.2.25 on 2025-10-08 12:19

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('itinerarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('codigo_qr', models.ImageField(blank=True, null=True, upload_to='tickets/qr/')),
                ('fecha_emision', models.DateTimeField(auto_now_add=True)),
                ('fecha_validez', models.DateField(help_text='Fecha hasta la cual es válido el ticket')),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('usado', 'Usado'), ('vencido', 'Vencido'), ('cancelado', 'Cancelado')], default='activo', max_length=20)),
                ('fecha_uso', models.DateTimeField(blank=True, null=True)),
                ('validado_por', models.CharField(blank=True, help_text='Usuario/sistema que validó', max_length=200)),
                ('itinerario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ticket', to='itinerarios.itinerario')),
            ],
            options={
                'verbose_name': 'Ticket',
                'verbose_name_plural': 'Tickets',
                'ordering': ['-fecha_emision'],
            },
        ),
    ]
